idf_component_register(
    SRCS
        "main.cc"
        "model_data.cc"
        "audio_ring.cc"
        "audio_capture.cc"
        "wav_injector.cc"
        "mfcc.cc"
        "tflm.cc"
        "logits_test.cc"
        "trigger.cc"
        "vad.cc"
        "netwrap.cc"
        "streamer.cc"
        "power_mgr.cc"
        "vad_calib.cc"
        "watchdog.cc"
        "boot_guard.cc"
        "health_diag.cc"
    INCLUDE_DIRS
        "."
    REQUIRES
        tflm
        esp_driver_i2s
        esp_driver_gpio
        esp_timer
        nvs_flash
        esp_wifi
        esp_netif
        lwip
        esp_pm
        esp_hw_support
)
