#!/usr/bin/env python3
"""
gen_mfcc_goldens.py — Golden Export for Spectra KWS MFCC Engine

Generates:
  1. firmware/spectra/main/hann_table.h      (1024-pt periodic Hann window)
  2. firmware/spectra/main/twiddle_table.h   (512-pt complex twiddle factors)
  3. firmware/spectra/main/mel_table.h       (128x513 sparse Slaney Mel filterbank)
  4. firmware/spectra/main/dct_table.h       (40x128 Type-II ortho DCT matrix)
  5. firmware/tests/mfcc_goldens.bin         (>=50 clips with bit-exact reference outputs)

Desktop Ground Truth: scripts/audio_utils.py
"""

import os
import sys
import glob
import struct
import numpy as np
import scipy.signal
import scipy.fftpack
import librosa

# Paths
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "scripts"))
from audio_utils import (
    SAMPLE_RATE, TARGET_SAMPLES, N_MFCC, N_FFT, HOP_LENGTH, N_FRAMES,
    load_and_fix_audio, normalize_amplitude, quantize_to_int8
)

MAIN_DIR = os.path.join(PROJECT_ROOT, "firmware", "spectra", "main")
TESTS_DIR = os.path.join(PROJECT_ROOT, "firmware", "tests")
SPLITS_DIR = os.path.join(PROJECT_ROOT, "dataset", "splits", "test")

# Contract Constants
N_MELS = 128
SCALE = 3.9962144
ZERO_POINT = 60


def export_hann_table():
    """Periodic Hann window of length 1024: w[n] = 0.5 - 0.5*cos(2*pi*n/1024)"""
    w = scipy.signal.windows.hann(N_FFT, sym=False).astype(np.float32)
    w_q15 = np.round(w * 32767.0).clip(0, 32767).astype(np.int16)

    out_path = os.path.join(MAIN_DIR, "hann_table.h")
    with open(out_path, "w") as f:
        f.write("/**\n * hann_table.h — 1024-point Periodic Hann Window\n")
        f.write(f" * Generated by gen_mfcc_goldens.py (scipy {scipy.__version__})\n */\n\n")
        f.write("#ifndef HANN_TABLE_H_\n#define HANN_TABLE_H_\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define SPECTRA_HANN_LEN {N_FFT}\n\n")

        # Float table
        f.write("static const float kHannWindowFloat[SPECTRA_HANN_LEN] = {\n")
        for i, val in enumerate(w):
            f.write(f"    {val:.9e}f,")
            if (i + 1) % 4 == 0:
                f.write("\n")
        f.write("};\n\n")

        # Q15 table
        f.write("static const int16_t kHannWindowQ15[SPECTRA_HANN_LEN] = {\n")
        for i, val in enumerate(w_q15):
            f.write(f"    {val},")
            if (i + 1) % 8 == 0:
                f.write("\n")
        f.write("};\n\n")
        f.write("#endif  // HANN_TABLE_H_\n")

    print(f"[EXPORT] {out_path}: {len(w)} points (max={np.max(w):.6f})")


def export_twiddle_table():
    """512 complex twiddle factors for 1024-point Radix-2 DIT FFT"""
    N = N_FFT
    half_N = N // 2  # 512
    k = np.arange(half_N)
    angle = -2.0 * np.pi * k / N
    tw_cos = np.cos(angle).astype(np.float32)
    tw_sin = np.sin(angle).astype(np.float32)

    tw_cos_q15 = np.round(tw_cos * 32767.0).clip(-32768, 32767).astype(np.int16)
    tw_sin_q15 = np.round(tw_sin * 32767.0).clip(-32768, 32767).astype(np.int16)

    out_path = os.path.join(MAIN_DIR, "twiddle_table.h")
    with open(out_path, "w") as f:
        f.write("/**\n * twiddle_table.h — 512-point Complex Twiddle Factors (W_1024^k)\n")
        f.write(f" * Generated by gen_mfcc_goldens.py (numpy {np.__version__})\n */\n\n")
        f.write("#ifndef TWIDDLE_TABLE_H_\n#define TWIDDLE_TABLE_H_\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define SPECTRA_TWIDDLE_LEN {half_N}\n\n")

        # Float cos
        f.write("static const float kTwiddleCosFloat[SPECTRA_TWIDDLE_LEN] = {\n")
        for i, val in enumerate(tw_cos):
            f.write(f"    {val:.9e}f,")
            if (i + 1) % 4 == 0:
                f.write("\n")
        f.write("};\n\n")

        # Float sin
        f.write("static const float kTwiddleSinFloat[SPECTRA_TWIDDLE_LEN] = {\n")
        for i, val in enumerate(tw_sin):
            f.write(f"    {val:.9e}f,")
            if (i + 1) % 4 == 0:
                f.write("\n")
        f.write("};\n\n")

        # Q15 cos
        f.write("static const int16_t kTwiddleCosQ15[SPECTRA_TWIDDLE_LEN] = {\n")
        for i, val in enumerate(tw_cos_q15):
            f.write(f"    {val},")
            if (i + 1) % 8 == 0:
                f.write("\n")
        f.write("};\n\n")

        # Q15 sin
        f.write("static const int16_t kTwiddleSinQ15[SPECTRA_TWIDDLE_LEN] = {\n")
        for i, val in enumerate(tw_sin_q15):
            f.write(f"    {val},")
            if (i + 1) % 8 == 0:
                f.write("\n")
        f.write("};\n\n")
        f.write("#endif  // TWIDDLE_TABLE_H_\n")

    print(f"[EXPORT] {out_path}: {half_N} twiddles")


def export_mel_table():
    """128x513 Slaney Mel Filterbank in sparse CSR representation"""
    mel_fb = librosa.filters.mel(
        sr=SAMPLE_RATE, n_fft=N_FFT, n_mels=N_MELS, fmin=0.0, fmax=SAMPLE_RATE/2.0,
        htk=False, norm='slaney'
    ).astype(np.float32)

    total_elements = 0
    sparse_info = []
    flat_weights = []

    for m in range(N_MELS):
        row = mel_fb[m]
        non_zero = np.where(row > 1e-12)[0]
        if len(non_zero) == 0:
            start_bin = 0
            n_bins = 0
        else:
            start_bin = int(non_zero[0])
            end_bin = int(non_zero[-1])
            n_bins = end_bin - start_bin + 1
            weights = row[start_bin:end_bin + 1].tolist()
            flat_weights.extend(weights)
            total_elements += n_bins
        sparse_info.append((start_bin, n_bins))

    out_path = os.path.join(MAIN_DIR, "mel_table.h")
    with open(out_path, "w") as f:
        f.write("/**\n * mel_table.h — Sparse 128x513 Slaney Mel Filterbank\n")
        f.write(f" * Generated by gen_mfcc_goldens.py (librosa {librosa.__version__})\n */\n\n")
        f.write("#ifndef MEL_TABLE_H_\n#define MEL_TABLE_H_\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define SPECTRA_N_MELS       {N_MELS}\n")
        f.write(f"#define SPECTRA_FFT_BINS     {(N_FFT // 2) + 1}\n")
        f.write(f"#define SPECTRA_MEL_WEIGHTS  {total_elements}\n\n")

        # Bin intervals
        f.write("typedef struct {\n    uint16_t start_bin;\n    uint16_t count;\n} mel_filter_desc_t;\n\n")
        f.write("static const mel_filter_desc_t kMelFilters[SPECTRA_N_MELS] = {\n")
        for m, (start, count) in enumerate(sparse_info):
            f.write(f"    {{{start}, {count}}},  // Mel filter {m}\n")
        f.write("};\n\n")

        # Flat non-zero weights
        f.write("static const float kMelWeights[SPECTRA_MEL_WEIGHTS] = {\n")
        for i, val in enumerate(flat_weights):
            f.write(f"    {val:.9e}f,")
            if (i + 1) % 4 == 0:
                f.write("\n")
        f.write("\n};\n\n")
        f.write("#endif  // MEL_TABLE_H_\n")

    print(f"[EXPORT] {out_path}: {N_MELS} filters, {total_elements} non-zero weights (~{total_elements*4} bytes, vs dense {128*513*4} bytes)")


def export_dct_table():
    """40x128 Type-II Orthonormal DCT matrix"""
    dct_mat = scipy.fftpack.dct(np.eye(N_MELS, dtype=np.float32), type=2, norm='ortho', axis=0)[:N_MFCC]

    out_path = os.path.join(MAIN_DIR, "dct_table.h")
    with open(out_path, "w") as f:
        f.write("/**\n * dct_table.h — 40x128 Type-II Orthonormal DCT Matrix\n")
        f.write(f" * Generated by gen_mfcc_goldens.py (scipy {scipy.__version__})\n */\n\n")
        f.write("#ifndef DCT_TABLE_H_\n#define DCT_TABLE_H_\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define SPECTRA_N_MFCC {N_MFCC}\n")
        f.write(f"#define SPECTRA_N_MELS {N_MELS}\n\n")
        f.write("static const float kDctMatrix[SPECTRA_N_MFCC][SPECTRA_N_MELS] = {\n")
        for k in range(N_MFCC):
            f.write("    {  // Coefficient " + str(k) + "\n")
            for m in range(N_MELS):
                f.write(f"        {dct_mat[k, m]:.9e}f,")
                if (m + 1) % 4 == 0:
                    f.write("\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write("#endif  // DCT_TABLE_H_\n")

    print(f"[EXPORT] {out_path}: {N_MFCC}x{N_MELS} DCT matrix (max={np.max(np.abs(dct_mat)):.6f})")


def generate_golden_clips():
    """Builds mfcc_goldens.bin with >= 50 real clips (25 pos + 25 neg)"""
    pos_files = sorted(glob.glob(os.path.join(SPLITS_DIR, "positive", "*.wav")))
    neg_files = sorted(glob.glob(os.path.join(SPLITS_DIR, "negative", "*.wav")))

    # Prioritize synth hard negatives in negative set
    synth_neg = [f for f in neg_files if "synth_" in os.path.basename(f)]
    other_neg = [f for f in neg_files if "synth_" not in os.path.basename(f)]
    selected_neg = (synth_neg + other_neg)[:25]
    selected_pos = pos_files[:25]

    selected_files = []
    for f in selected_pos:
        selected_files.append((f, "positive", 0))
    for f in selected_neg:
        is_hard = 1 if "synth_" in os.path.basename(f) else 0
        selected_files.append((f, "negative", is_hard))

    assert len(selected_files) >= 50, f"Expected >= 50 clips, found {len(selected_files)}"

    out_bin = os.path.join(TESTS_DIR, "mfcc_goldens.bin")
    with open(out_bin, "wb") as f:
        # Header (128 bytes)
        magic = b"SPMF"
        version = 1
        n_clips = len(selected_files)
        librosa_ver = librosa.__version__.encode('utf-8')[:32].ljust(32, b'\0')
        scipy_ver = scipy.__version__.encode('utf-8')[:32].ljust(32, b'\0')
        numpy_ver = np.__version__.encode('utf-8')[:32].ljust(32, b'\0')

        header = struct.pack(
            "<4sIIIIII32s32s32s",
            magic, version, n_clips, SAMPLE_RATE, TARGET_SAMPLES, N_MFCC, N_FRAMES,
            librosa_ver, scipy_ver, numpy_ver
        )
        f.write(header)

        for filepath, label, is_hard in selected_files:
            fname = os.path.basename(filepath).encode('utf-8')[:64].ljust(64, b'\0')
            lbl = label.encode('utf-8')[:16].ljust(16, b'\0')

            # 1. Load exact 1.0s audio
            y = load_and_fix_audio(filepath)

            # 2. Input PCM integer samples as produced by I2S microphone
            pcm_int16 = np.round(y * 32767.0).clip(-32768, 32767).astype(np.int16)
            max_int = int(np.max(np.abs(pcm_int16)))
            max_amp = float(max_int) / 32768.0

            if max_int > 0:
                pcm_norm = (pcm_int16.astype(np.float32) / float(max_int)).astype(np.float32)
            else:
                pcm_norm = np.zeros(TARGET_SAMPLES, dtype=np.float32)

            # 3. Extract reference MFCC using librosa truth on normalized PCM
            ref_mfcc = librosa.feature.mfcc(
                y=pcm_norm, sr=SAMPLE_RATE, n_mfcc=N_MFCC, n_fft=N_FFT, hop_length=HOP_LENGTH
            )[:, :N_FRAMES].astype(np.float32)

            # 4. Quantize to INT8 using banker's rounding
            ref_int8 = quantize_to_int8(ref_mfcc, SCALE, ZERO_POINT)

            # Write clip entry
            f.write(fname)
            f.write(lbl)
            f.write(struct.pack("<If", is_hard, max_amp))
            f.write(pcm_int16.tobytes())
            f.write(ref_mfcc.tobytes())
            f.write(ref_int8.tobytes())

    file_size = os.path.getsize(out_bin)
    print(f"[EXPORT] {out_bin}: {len(selected_files)} clips, {file_size} bytes (~{file_size/1024:.1f} KB)")


if __name__ == "__main__":
    print("=== Generating Spectra MFCC Golden Tables & Vectors ===")
    export_hann_table()
    export_twiddle_table()
    export_mel_table()
    export_dct_table()
    generate_golden_clips()
    print("=== All Golden Exports Completed Successfully ===")
